### ISSUE TITLE
Android 14 (API 34) instant crash

### ISSUE THREAD

**Issue by booooohdan** [alan-ai/alan-sdk-flutter#20]
Please add support for Android 14 (API 34)

One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

RemoteException
Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:16590)
	at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(IActivityManager.java:11530)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2928)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3195)
	at android.os.Binder.execTransactInternal(Binder.java:1375)

<img width="1062" alt="Знімок екрана 2024-04-16 о 23 19 25" src="https://github.com/alan-ai/alan-sdk-flutter/assets/30977443/b8a4f973-9a2f-4673-8da6-5e686e21b749">

**Comment by snyuryev** [comment]
Hi @booooohdan 
New version of AlanSDK for Flutter is released - https://pub.dev/packages/alan_voice/versions/4.8.0
Could you try this one and let us know is it working for you?

**Comment by booooohdan** [comment]
Yes, it's working now
